### ISSUE TITLE
Curseforge description is wrong

### ISSUE THREAD

**Issue by Samisaprogrammer** [MattCzyr/NaturesCompass#100]
In CF it says in the install instructions to install forge
![image](https://user-images.githubusercontent.com/59611020/125435775-dfded417-bdda-4480-be4f-0d6f8a48071e.png)
However the files are for fabric
![image](https://user-images.githubusercontent.com/59611020/125435877-5791996f-ccd0-4a87-a591-f6aabe52fc44.png)
![image](https://user-images.githubusercontent.com/59611020/125435905-39f1987d-049d-41a9-bfb7-59d5e336d16c.png)
Please update and thank you!

**Comment by MattCzyr** [comment]
I'll update the description to include installation instructions for Fabric, however there are also Forge files available if you view all the files.

**Comment by Samisaprogrammer** [comment]
alright cool ty
