### ISSUE TITLE
(FABRIC) Incompatible with First Person Model 1.17

### ISSUE THREAD

**Issue by Boolaura** [MattCzyr/NaturesCompass#102]
When attempting to open FirstPersonModel along with this mod installed, the game doesn't even reach the loading screen before crashing.
[crash-2021-07-21_17.26.59-client.txt](https://github.com/MattCzyr/NaturesCompass/files/6859372/crash-2021-07-21_17.26.59-client.txt)

**Comment by MattCzyr** [comment]
This could be fixed by either of us removing/renaming the client field from our HUD mixins, but because it's a simple fix I'll handle it and release the fix with the next update.

**Comment by MattCzyr** [comment]
Fixed in version 2.0.1-fabric.
