### ISSUE TITLE
Cant find 16.5 for forge

### ISSUE THREAD

**Issue by J40ck** [MattCzyr/NaturesCompass#104]
I was trying to download the mod and minecraft told me that it was a fabric mod, i go back and try to download the right version and it wasnt on curseforge or anything. there is only version 17.1 for forge and 16.5 for fabric, i cant download forge for 17.1 because i play minecraft in 16.5 and all my other mods are in 16.5. please someone tell me that its not just me. and also please fix it i really like this mod😭

**Comment by MattCzyr** [comment]
Check the files tab on CurseForge to see all the files. [This](https://www.curseforge.com/minecraft/mc-mods/natures-compass/files/3382150) is the latest version for Forge 1.16.5.
