### ISSUE TITLE
I need help...

### ISSUE THREAD

**Issue by TheSpyKid0906** [MattCzyr/NaturesCompass#111]
I have installed this mod and It's not working, I don't understand why though so if you can tell me... _why_
I really would like to try this mod and really like what I see I just can't use it.
[Screenshot 2021-10-08 210800](https://user-images.githubusercontent.com/92191558/136638529-a78eb971-26f8-48f2-a512-95c32b7fec6c.png)
 
[Screenshot 2021-10-08 211158](https://user-images.githubusercontent.com/92191558/136638683-fc9287c6-c671-4f13-b453-b6adcb88e378.png)

EDIT:
Yes I did use fabric api I tried that just now, still with it not working

**Comment by TheSpyKid0906** [comment]
> I have installed this mod and It's not working, I don't understand why though so if you can tell me... _why_ I really would like to try this mod and really like what I see I just can't use it. [Screenshot 2021-10-08 210800](https://user-images.githubusercontent.com/92191558/136638529-a78eb971-26f8-48f2-a512-95c32b7fec6c.png)
> 
> [Screenshot 2021-10-08 211158](https://user-images.githubusercontent.com/92191558/136638683-fc9287c6-c671-4f13-b453-b6adcb88e378.png)

**Comment by TheSpyKid0906** [comment]
![Screenshot 2021-10-10 110323](https://user-images.githubusercontent.com/92191558/136701512-eb7593dc-cdaf-410d-b95c-c0f382ade5e5.png)

so... what does _this_ mean

**Comment by MattCzyr** [comment]
You're trying to use the Forge version of Nature's Compass with the Fabric loader. Use the Fabric version of Nature's Compass instead.

**Comment by TheSpyKid0906** [comment]
Thank you!
