### ISSUE TITLE
Game Crash When Locating Twist's Charred Wastes

### ISSUE THREAD

**Issue by Phweeeee** [MattCzyr/NaturesCompass#115]
[debug.log](https://github.com/MattCzyr/NaturesCompass/files/7392909/debug.log)
[latest.log](https://github.com/MattCzyr/NaturesCompass/files/7392910/latest.log
[crash-2021-10-21_16.20.20-server.txt](https://github.com/MattCzyr/NaturesCompass/files/7392911/crash-2021-10-21_16.20.20-server.txt)
)

**Comment by ron4821** [comment]
I am having a similar issue..
[crash-report.txt](https://github.com/MattCzyr/NaturesCompass/files/7551514/crash-reports_crash-2021-11-16_22.17.24-server.txt)

**Comment by ron4821** [comment]
What was the fix?

**Comment by MattCzyr** [comment]
This seems to be an issue caused by one of the loaded mixins rather than by Nature's Compass, since the method BiomeManager.getBiome isn't meant to throw an IllegalStateException. I may fix it in the next release, however I'm also interested if @Phweeeee figured out what was causing it.
