### ISSUE TITLE
Launch problem

### ISSUE THREAD

**Issue by Moliatys** [MattCzyr/NaturesCompass#117]
I don't launch game but I don't know for what...
![Capture](https://user-images.githubusercontent.com/93333353/139276123-0b1bb65e-bfe4-4565-a78d-635d2f3220f0.PNG)

**Comment by MattCzyr** [comment]
Do you have the Fabric API installed in your mods folder? You need to install the Fabric API (you can find it on CurseForge) as well as the Fabric mod loader in order to use Fabric mods.

**Comment by Moliatys** [comment]
Thank you !!!!!
