### ISSUE TITLE
Recipe only works with vanilla trees, and not even all of those

### ISSUE THREAD

**Issue by UnixRonin** [MattCzyr/NaturesCompass#12]
The crafting recipe for the Nature's Compass uses a vanilla compass, minecraft:sapling, and minecraft:log.  The problem with this is that it does not cover even all vanilla Minecraft logs (some of which are minecraft:log2), let alone logs and saplings from mod-added trees.

If the recipe is changed to use ore:treeSapling and ore:logWood instead, it will work with all vanilla and mod-added logs and saplings.  (I've verified this using MineTweaker/CraftTweaker.)

**Comment by MattCzyr** [comment]
Recipe was (stealthily) changed to use ore dictionary logs in 1.12.2 update.
