### ISSUE TITLE
1.18.1 - Forge - Nature's Compass entounters an error during the common setup phase 

### ISSUE THREAD

**Issue by RosyBow** [MattCzyr/NaturesCompass#121]
Hi, I have an issue that started today when launching the server via aternos. I added the crash report, thank you in advanced!

[crash-2021-12-20.txt](https://github.com/MattCzyr/NaturesCompass/files/7748599/crash-2021-12-20.txt)

**Comment by ModernGamingWorld** [comment]
@RosyBow Its due to this new forge breaking change
Build: 1.18.1-39.0.7 - Mon Dec 20 18:35:11 GMT 2021
    JTK222:
        Redo of the whole PermissionAPI (#7780)

**Comment by RosyBow** [comment]
Oh that makes sense thank you! To fix it, I would use forge version?

**Comment by ModernGamingWorld** [comment]
> Oh that makes sense, thank you! To fix it, I would use 39.0.5 version of forge?

Yes Just Downgrade forge one versions for now

**Comment by RosyBow** [comment]
Thank so much for your help!

**Comment by ModernGamingWorld** [comment]
@MattCzyr will still have to fix this, so just watch for a fix and once it out you should be able to update to the new forge version

**Comment by MattCzyr** [comment]
Will work on compatibility with Forge >= 39.0.7 later today.

**Comment by MattCzyr** [comment]
Fixed in version 1.9.4.
