### ISSUE TITLE
1.18.1 Crash on first start up

### ISSUE THREAD

**Issue by VallenFrostweaver** [MattCzyr/NaturesCompass#122]
Minecraft 1.18.1
Forge 39.0.7
Nature's Compass 1.9.3

[Crash report on Hastebin](https://www.toptal.com/developers/hastebin/kinapegogi.properties)

**Comment by aAndrew3030** [comment]
I am having the same issue, switching to forge 39.0.6 fixes it

**Comment by aAndrew3030** [comment]
Same issue as
https://github.com/MattCzyr/NaturesCompass/issues/121

**Comment by red2blue** [comment]
![image](https://user-images.githubusercontent.com/35115304/147024454-2d60e691-5859-45fa-80bb-8f5be6f12c38.png)

same

**Comment by ModernGamingWorld** [comment]
Its due to Forge is rewrite of the Permission API

**Comment by red2blue** [comment]
How am i not surprised. Coming from fabric, such a huge impact on modloader
updates between the two.

**Comment by MattCzyr** [comment]
Will work on compatibility with Forge >= 39.0.7 later today.

**Comment by MattCzyr** [comment]
Fixed in version 1.9.4.
