### ISSUE TITLE
Compass does not work with non-vanilla terrain generation mods

### ISSUE THREAD

**Issue by UnixRonin** [MattCzyr/NaturesCompass#13]
I have a 1.10.2 modpack containing 86 mods, several of which add biomes.  Nature's Compass picks up all of the new biomes without issue.  The problem is I **ALSO** have a non-vanilla terrain generator, RTG — but it appears Nature's Compass doesn't indicate where the nearest requested biome **is**, it indicates where NC thinks that biome **should be** assuming vanilla terrain generation.  If a non-vanilla terrain generation mod is in use, this assumption completely breaks down and it points to completely the wrong places.

I don't know whether this is in practical terms fixable, or whether it should just be documented as a limitation that it will not work with alternate terrain generators.

**Comment by renandadalte** [comment]
Same issue here with a custom modpack with 200+ mods and Terraforged generation. MC 1.16.5 Forge 36.1.0

**Comment by Macleykun** [comment]
Technically this is also related to https://github.com/MattCzyr/NaturesCompass/issues/14
Link it here, incase either one get's an update.

**Comment by MattCzyr** [comment]
Just tested with Realistic Terrain Generation and TerraForged, and both worked as intended. I have to assume this is an issue of the biomes you're trying to find being too far away to locate with your current config settings. Please check my response on #14 for more info.
