### ISSUE TITLE
Entrypoint crash

### ISSUE THREAD

**Issue by Flyvee** [MattCzyr/NaturesCompass#132]
A user on my server is the only one experiencing this crash when they are trying to launch minecraft. They are running fabric 13.3 for minecraft 1.18.1 and the mod has been updated to the latest version for 1.18.1, namely the 2.0.3 version. She is using a windows pc and have 3gb ram allocated to minecraft so I'm unsure myself what is causing the problem.
[Here.txt](https://github.com/MattCzyr/NaturesCompass/files/8468440/Here.txt)

**Comment by MattCzyr** [comment]
Looks like the user's Nature's Compass config file might be corrupted. Ask them to try deleting it so it can be re-generated.
