### ISSUE TITLE
[1.18.2-Forge] Very uncommon crash upon starting client.

### ISSUE THREAD

**Issue by Gbergz** [MattCzyr/NaturesCompass#133]
Seems to be very rare as I've only gotten it a few times.

MC: 1.18.2
Forge: 40.1.0
Nature's Compass: 1.9.5-Forge

Crash-Report: https://gist.github.com/Gbergz/2e4ff384d8257f6dbe24e2a3538bcebe

**-** Gbergz

**Comment by MaxWasUnavailable** [comment]
Can confirm I had this crash occur as well.

**Comment by MattB70** [comment]
Having it as well, no other info is provided though, sorry.

**Comment by MattCzyr** [comment]
Should be fixed in versions 1.19-1.9.7-forge and 1.18.2-1.9.7-forge.
