### ISSUE TITLE
1.16.5 Mod Loading Crash Report

### ISSUE THREAD

**Issue by ElyMariane** [MattCzyr/NaturesCompass#142]
I repeatedly try to open my game in Minecraft version 1.16.5 with some mods but I just can't do it because of the fabrics. I already tried to install Fabric on my computer but it didn't help, and I'm not able to download the Fabric API because the installer doesn't open.

**Comment by MattCzyr** [comment]
Sounds like this is an issue with an incorrect installation of Fabric, not with this mod itself. Make sure Fabric is installed, and make sure you have the Fabric API jar present in your mods folder.
