### ISSUE TITLE
[Question] Dimensions with different seeds

### ISSUE THREAD

**Issue by clmc99** [MattCzyr/NaturesCompass#144]
I have a world where the Nether and End are generated with a different seed than the Overworld. It seems like Nature's Compass uses the overall world seed (the one that was used to generate the Overworld) instead of the per-dimension seed. Is there a way to change this?

**Comment by MattCzyr** [comment]
Seeds should have no impact on how the compass works. When you search for a biome, evenly spaced samples are taken spiraling outward from your starting location. The biome is checked at each of these locations, and if it matches the biome you're searching for, it succeeds. It isn't linked to the world seed.

**Comment by clmc99** [comment]
Hmm, it's not finding the right biomes for me in the Nether or End
