### ISSUE TITLE
1.19.2 MineColonies pack incorrect biomes

### ISSUE THREAD

**Issue by EliotWL** [MattCzyr/NaturesCompass#145]
So I am playing on 1.19.2 on the official MineColonies modpack but I added this mod to help find biomes and it does seem to work like 90% of the time, but every once in awhile I go to one of the locations and it's the completely wrong biome. My most recent was searching for a vanilla Swamp biome, and ended up in just the middle of the ocean.  
![image](https://user-images.githubusercontent.com/39184025/190543899-733e7176-c510-4306-aa6b-d42c4b2652b0.png)
Figured I'd submit the bug report in case one of these mods comes up again as causing problems.  (Only mods I've added to the modlist outside of the main MineColonies Official modpack is this compass and Iron Chests)

**Comment by MattCzyr** [comment]
You're at the wrong coordinates. The swamp is at -4833 927, not 927 -4833.
