### ISSUE TITLE
Can't locate Deep Dark

### ISSUE THREAD

**Issue by CapoFantasma97** [MattCzyr/NaturesCompass#147]
When trying to locate Deep Dark it says theresn't one in a 10 thousands block range.
But /locate biome minecraft:deep_dark finds it. Once the command is run, Nature's Compass will point to it.

Minecraft 1.19.2
Quilt Loader 0.17.4
Java 17

**Comment by MattCzyr** [comment]
Yes, for now the compass only searches horizontally in your current Y-plane. This is something I'll probably change in the near future, but for now, if you're trying to find a cave biome you should go down to around where they generate before searching.

**Comment by MattCzyr** [comment]
Fixed in latest versions, 1.10.0-forge and 2.1.0-fabric.
