### ISSUE TITLE
'Error: Timed out' even when I'm on singleplayer

### ISSUE THREAD

**Issue by VoidVector10** [MattCzyr/NaturesCompass#16]
I'm not using any biome adding mod, but when I use the compass to search for a biome the whole games freezes, although my player can move, and eventually I get the message of connection timed out, even when I'm not on a server, or playing on Lan with anybody, as I'm playing in my own personal world.

**Comment by MattCzyr** [comment]
The algorithm for finding a biome is quite resource intensive, and it sounds like it's taking too long to locate whatever biome you're trying to find. Just as a test, can you try locating a biome that you know is very close to your current position and see if the game still times out? After that, you can try some combination of lowering distanceModifier, lowering maxSamples, and increasing sampleSpaceModifier in naturescompass.cfg. I recommend mainly changing distanceModifier; with a lower distance modifier you won't be able to locate biomes that are extremely far away, but it may stop the game from timing out.

**Comment by Sakata-MC** [comment]
The algorithm should likely be changed to have non-blocking wait(s).  This would prevent disconnects

**Comment by MattCzyr** [comment]
Fixed in version 1.8.0 with the use of a worker to perform biome searches
