### ISSUE TITLE
Crash on Fabric for 1.20

### ISSUE THREAD

**Issue by PaleDerp** [MattCzyr/NaturesCompass#160]
Mod causes crash on the latest version of fabric for 1.20. I ran fabric by it's self and it worked fine. 

I've never made a crash report before hopefully this works. I've added the log and crash report. The log is from an instance of just Minecraft, fabric, and Natures Compass. 

Thank you

[latest.log](https://github.com/MattCzyr/NaturesCompass/files/11779678/latest.log)

[crash-2023-06-17_12.36.02-client.txt](https://github.com/MattCzyr/NaturesCompass/files/11779681/crash-2023-06-17_12.36.02-client.txt)

**Comment by MattCzyr** [comment]
Fixed in version 1.20-2.2.2-fabric.
