### ISSUE TITLE
Possible conflict with Advanced Compass

### ISSUE THREAD

**Issue by Gamemassa** [MattCzyr/NaturesCompass#163]
Forge 1.20.1

I'm getting odd text overlapping with Advanced Compass and I'm not sure why. It appears to be duplicating the Nature's Compass text, but when I go to adjust the Y-offset in Advanced Compass settings it moves the duplicated text. (I've posted this in their Issues thread as well.

![image](https://github.com/MattCzyr/NaturesCompass/assets/18667108/12495053-8c89-49b2-b192-cbb6f84b607f)

**Comment by MattCzyr** [comment]
It looks like the Advanced Compass mod isn't open source, so I really have no way of figuring out what's going on here. I suspect Advanced Compass is also doing its rendering in `RenderGuiOverlayEvent` and is somehow refiring the `Post` event. I saw you also opened an issue on the Advanced Compass CurseForge page, so we'll see if there's any response there.

**Comment by Gamemassa** [comment]
What's even weirder is that this didn't happen back when I had my custom modpack in 1.19.x, but now in 1.20.x it's doing this. I'm not entirely sure what would've changed.

**Comment by teagan75** [comment]
> @MattCzyr Edit - This is happening with Explorer's Compass too.

I can verify that this is also happening with Explorer's Compass in 1.20.1

**Comment by MattCzyr** [comment]
Should be fixed in version 1.11.5.
