### ISSUE TITLE
[crash] On teleport in the end

### ISSUE THREAD

**Issue by CKY-** [MattCzyr/NaturesCompass#164]
[https://gist.github.com/CKY-/9b02c503f45dcc30092ad7d52b32adca](https://gist.github.com/CKY-/9b02c503f45dcc30092ad7d52b32adca)

when n the end click on a dimension and click teleport results in the world to stop loading, with no errors until you do this in a server and get watchdog involved here is the error that is the result 
	FML: 43.2
	Forge: net.minecraftforge:43.2.14
	Minecraft: 1.19.2
	NaturesCompass-1.19.2-1.10.0-forge

**Comment by MattCzyr** [comment]
Fixed in versions 1.11.2-forge and 2.2.3-fabric.
