### ISSUE TITLE
Can't see distance

### ISSUE THREAD

**Issue by CaptainIsHere** [MattCzyr/NaturesCompass#17]
So while using the Nature's Compass mod, the coordinates and distances are on the bottom left of my screen. However, the distance number is actually cut off from my screen so I can't see how far a biome is from my location. I've changed the resolution and that isn't the problem. Any suggestions?

**Comment by Knito58** [comment]
Maybe changing the screen font settings can help.

**Comment by CaptainIsHere** [comment]
![image](https://user-images.githubusercontent.com/39394447/40275492-218827ee-5bbe-11e8-9082-fbdd5d7c94f7.png)

**Comment by CaptainIsHere** [comment]
![image](https://user-images.githubusercontent.com/39394447/40275496-2dcd2c70-5bbe-11e8-8ea2-eba2462ad521.png)

**Comment by CaptainIsHere** [comment]
![image](https://user-images.githubusercontent.com/39394447/40275503-5d9aee38-5bbe-11e8-806a-dcc7a1019301.png)

**Comment by Knito58** [comment]
Make your Windows Bar "hide automatically".

**Comment by Knito58** [comment]
Or run Minecraft in a window instead of full screen. Then you can resize the border sparing out the bar. I do that.

**Comment by MattCzyr** [comment]
You could decrease lineOffset in naturescompass.cfg by one or two so that the information appears a couple lines up.

**Comment by CaptainIsHere** [comment]
Changing the GUI scale worked.
