### ISSUE TITLE
[Fabric 1.20.4] A parsing error loading custom advancement shows up in the logs

### ISSUE THREAD

**Issue by kingkuys2123** [MattCzyr/NaturesCompass#172]
Minecraft 1.20.4
Fabric 0.15.3
Fabric API 0.91.3
Java 20.0.2
NaturesCompass 2.2.3

## **ISSUE**
A parsing error loading custom advancement shows up in the logs

## **LOG**
```[13:50:35] [Render thread/ERROR]: Parsing error loading custom advancement naturescompass:natures_compass: Not a json array: "minecraft:compass" missed input: {"has_compass":{"trigger":"minecraft:inventory_changed","conditions":{"items":[{"items":"minecraft:compass"}]}}}```

**Comment by kingkuys2123** [comment]
Here's a fix for 
```
{
  "parent": "minecraft:recipes/root",
  "rewards": {
    "recipes": [
      "naturescompass:natures_compass"
    ]
  },
  "criteria": {
    "has_compass": {
      "trigger": "minecraft:inventory_changed",
      "conditions": {
        "items": [
          {
            "item": "minecraft:compass"
          }
        ]
      }
    },
    "has_recipe": {
      "trigger": "minecraft:recipe_unlocked",
      "conditions": {
        "recipe": "naturescompass:natures_compass"
      }
    }
  },
  "requirements": [
    [
      "has_compass",
      "has_recipe"
    ]
  ]
}
```

**Comment by IguanaParty** [comment]
@kingkuys2123 Where is this bit of code going? Should it be placed naturescompass.json file or somewhere else?

**Comment by kingkuys2123** [comment]
[naturescompass.json](https://github.com/MattCzyr/NaturesCompass/blob/master/src/main/resources/data/naturescompass/advancements/natures_compass.json)

**Comment by kingkuys2123** [comment]
[naturescompass.json](https://github.com/MattCzyr/NaturesCompass/blob/master/src/main/resources/data/naturescompass/advancements/natures_compass.json)
