### ISSUE TITLE
Offset Duplicated Overlay Text

### ISSUE THREAD

**Issue by madisonexx** [MattCzyr/NaturesCompass#175]
![Screenshot (245)](https://github.com/MattCzyr/NaturesCompass/assets/160751421/58dd7369-2d3d-461a-a01e-bf030fd06399)
I saw #78, #163, and #168 but they are all attributed to mods I don't have installed. No Raised or Advanced Compass.

**Comment by MattCzyr** [comment]
Should be fixed in version 1.11.5.
