### ISSUE TITLE
[1.20.5] NeoForge and Fabric adding a c:hidden_from_locator_selection biome tag

### ISSUE THREAD

**Issue by TelepathicGrunt** [MattCzyr/NaturesCompass#177]
As part of the tag unification PRs here:
https://github.com/FabricMC/fabric/pull/3310
https://github.com/neoforged/NeoForge/pull/135

Both Fabric and NeoForge will add a `c:hidden_from_locator_selection` biome tag to allow biome makers specify if their biomes should not be locatable with modded items/abilities such as Nature's Compass. This could be for balance reasons or technical reasons or whatever.

This is just a heads up on this upcoming convention tag that you might be interested in having your mod check for to know what biomes to not allow users to locate with your item.

**Comment by MattCzyr** [comment]
Thanks for the heads up, I'll make use of this for both Nature's Compass and Explorer's Compass when updating to 1.20.5.

**Comment by MattCzyr** [comment]
Implemented in 2.2.4-fabric and 3.0.1-neoforge.
