### ISSUE TITLE
No crafting recipe for 1.20.6 version

### ISSUE THREAD

**Issue by NicholasRB** [MattCzyr/NaturesCompass#183]
I see the NeoForge 1.20.6 version currently available doesn't have a crafting recipe for it. Was that intentional? I know you can find them as loot, but I am also finding they are incredibly rare from my own creative world testing. I don't really have much else to say, but was wondering if that was just a mistake.

- Nick

**Comment by MattCzyr** [comment]
Definitely not intentional. Fixed in 3.0.2-neoforge, 2.2.5-fabric, and 1.11.6-forge.
