### ISSUE TITLE
Nature's Compass is uncraftable in 1.21.1

### ISSUE THREAD

**Issue by SnapsMcK** [MattCzyr/NaturesCompass#188]
Tried to craft the compass, triple-checked the recipe, JEI doesn't show a recipe for it. Compass is in the game, but it can't be crafted. I even tried to use it by itself to see if there was some other mod interfering with it, but the issue persists.
![Screenshot 2024-09-09 100738](https://github.com/user-attachments/assets/df15ccc0-4fc8-4146-9d03-58482a190e19)

**Comment by SnapsMcK** [comment]
I forgot to mention: I'm using Fabric

**Comment by goldenmasterly** [comment]
while hopefully Chaosyr fixes the problem
if you want a temporary solution use this a custom crafting recipe data pack just add it to your worlds data pack folder

[naturescompass.zip](https://github.com/user-attachments/files/16974157/naturescompass.zip)

**Comment by ticcitoasty** [comment]
tried adding the data pack and it still doesnt seem to work for fabric

**Comment by goldenmasterly** [comment]
> tried adding the data pack and it still doesnt seem to work for fabric

are you using specifically oak saps and logs as i couldn't figure out how to use other types of wood and saps

**Comment by goldenmasterly** [comment]
> tried adding the data pack and it still doesnt seem to work for fabric

open to lan and allow cheats and use the command /datapack enable [naturescompass.zip]

**Comment by MattCzyr** [comment]
Fixed in version 2.2.7
