### ISSUE TITLE
[1.16.5 Bug] Right click the compass does not consider as Using the compass

### ISSUE THREAD

**Issue by GoldenTotem** [MattCzyr/NaturesCompass#192]
Minecraft 1.16.5  Forge 36.2.35  Mod 1.9.1

If you place a nature compass in your mainhand and a snowball in your offhand, then right click. The gui will be opened while the snowball will be thrown too. 
It means the game does not consider right-clicking the nature compass as using it. 
Because in vanilla, if the mainhand item can be used, the using of offhand item will be disabled, which means items in your two hands cannot be used simultaneously.
In another word, if an item can be used, in Statistics / Items / Times used will show how many times it has been used. Obviously, because right-clicking nature compass does not consider as using it. Using times in statistics of nature compass will not change any more.

Mod [Explorer Compass](https://github.com/MattCzyr/ExplorersCompass) also has this problem.

Expect behaviors:
The right-clicking behaviors of compass use vanilla behaviors.

**Comment by MattCzyr** [comment]
Fixed in forge-1.11.8/fabric-2.2.8/neoforge-3.0.4.
