### ISSUE TITLE
Is this compatible with 1.21.1? 

### ISSUE THREAD

**Issue by ardunster** [MattCzyr/NaturesCompass#194]
There isn't a listed version for 1.21.1. From what I have read, changes from 1.21 to 1.21.1 are pretty minimal?  A lot of the other mods I want aren't updated to 1.21.3 at this point. Is it safe to just override and use the 1.21 version, or is there a better approach?

**Comment by ardunster** [comment]
I tried this and the game loaded fine and I was able, at least in creative, to craft a compass, search for a biome, and use it to teleport. Will report back if I run into any issues with it down the line.

**Comment by MattCzyr** [comment]
I assume you're using Modrinth, there were versions for 1.21.1 available on CurseForge but looks like I forgot to upload them to Modrinth. Just fixed that.

**Comment by ardunster** [comment]
Great, thanks! Yeah I am using modrinth.
