### ISSUE TITLE
1.10.2 Seaching for "The End" Biome in the overworld crashes client

### ISSUE THREAD

**Issue by JAWSAWN** [MattCzyr/NaturesCompass#2]
https://gist.github.com/JAWSAWN/1d0bd73121b16e81dfc2ae4cabee32a3

**Comment by MattCzyr** [comment]
Seems to be an issue with Biomes o' Plenty; occured only because Nature's Compass must load/generate chunks to search for an End biome. Nothing actually related to Nature's Compass in the stacktrace. Report it to BoP's issue tracker.
