### ISSUE TITLE
Crash on "Status Not Found"

### ISSUE THREAD

**Issue by DwarvenSteel25** [MattCzyr/NaturesCompass#20]
When using the compass in my modpack, if the searched for biome can't be located, the result is a timeout with 100% percent repeatable results. 

I am using RTG in my pack in case that affects things. This is with the latest version of the 1.10.2 which I realize is still more than a year old so no idea if this will be seen, but figured I'd submit the issue.

**Comment by phlaxyr** [comment]
+1 (I searched Energy Cell biome on E2E)

**Comment by phlaxyr** [comment]
I should note this is on mc ver. 1.12
https://pastebin.com/hct9erGw
