### ISSUE TITLE
Shift-right-click does not reset compass

### ISSUE THREAD

**Issue by akinnee** [MattCzyr/NaturesCompass#29]
Shift-right-click does the same thing as right-click. It opens the biome selection.

**Comment by akinnee** [comment]
Oh is it SNEAK right-click? I have my keys changed. 😆 Might want to update the docs if that's the case. I've gone over to vanilla 1.14.4 so I cannot test this anymore.

**Comment by MattCzyr** [comment]
It is indeed sneak-right-click, not shift-right-click. Thanks for reminding me to update the documentation.
