### ISSUE TITLE
Config may not be respecting disabled biomes

### ISSUE THREAD

**Issue by katubug** [MattCzyr/NaturesCompass#30]
Here is a link to my config: https://pastebin.com/U9q5rjz4

**Minecraft version**: 1.12.2
**Forge version**: forge-1.12.2-14.23.5.2846-universal
**Modpack version (links to current modlist)**: [1.7.0](http://enthusiasticraft.cf/modpack-update-1-7-0/#modlist)
**Mod versions**: NaturesCompass-1.12.2-1.5.1

Screenshots of the Nature's Compass menu: ![2019-09-10_16 32 33](https://user-images.githubusercontent.com/20935286/64652081-9c51f100-d3e8-11e9-8818-ffdd5895e11d.png)
![2019-09-10_16 32 22](https://user-images.githubusercontent.com/20935286/64652082-9c51f100-d3e8-11e9-83d8-b2321f69dc5e.png)

As you can see, though I have disabled the erroring biome and all the Twilight Forest biomes, they still show in the list. Have I formatted the config incorrectly?

Thank you for your time! :)

**Comment by MattCzyr** [comment]
Your formatting is correct but the current Nature's Compass release only supports blacklisting biomes by name or ID, not resource location. This change was merged quite a while ago but I haven't released 1.6.0 yet. In the mean time, replace the entries in the config with either biome names (i.e. Dark Forest) or numerical IDs.

**Comment by katubug** [comment]
Okay, thank you very much! Do you happen to know if there's a reliable way of discovering the numerical IDs? Google hasn't really helped, but I might be using poor search terms.

**Comment by MattCzyr** [comment]
There isn't really a straightforward way without third-party tools, but you can use the mod [TellMe](https://www.curseforge.com/minecraft/mc-mods/tellme) to figure it out pretty easily.

**Comment by katubug** [comment]
You're the best! Thank you for all the help! :)
