### ISSUE TITLE
Very nasty bug with random chunks appearing in the world

### ISSUE THREAD

**Issue by Darsenia** [MattCzyr/NaturesCompass#32]
Hello,
I came across one very bad bug with chunks while using nature compass.When I'm searching for the biome(it doesn't matter if the biome was found or not),looking through the biome list or sometimes simply holding a compass, some random "torn out" chunks from other biomes appear in the world near player location.
I'm using it with OTG,cause I'm working on my biome pack project and have to teleport a lot to check biomes.I have used Nature Compass a lot for a long time with other biome mods,but this bug I experience only with OTG(or I've been very lucky before).
I'm using
-Minecraft 1.12.2 
-Forge 14.23.5.2847 (I used different Forge versions,it doesn't matter)
-OpenTerrainGenerator v6
-latest Nature Compass 1.5.1
Here are some screenshots (sometimes biomes were found,sometimes not):
![2019-06-06_22 16 12](https://user-images.githubusercontent.com/36276289/66268576-4c2f4880-e847-11e9-9e51-0c1233e5d6e6.png)
![2019-07-03_22 17 54](https://user-images.githubusercontent.com/36276289/66268577-4c2f4880-e847-11e9-911a-04855b97873a.png)
![2019-08-05_22 50 47](https://user-images.githubusercontent.com/36276289/66268578-4cc7df00-e847-11e9-90f7-591b1166b5b9.png)

**Comment by MattCzyr** [comment]
Very, very unlikely that this is actually linked to Nature's Compass in any way since the mod doesn't mess with worldgen at all. More likely linked to OTG, but this can happen in vanilla as well.
