### ISSUE TITLE
Server crash on 1.6.0

### ISSUE THREAD

**Issue by sumrex** [MattCzyr/NaturesCompass#34]
Server crashes with version 1.6.0
Whenever anyone searches for a biome they get disconnected and locked out of the server. Sometimes the server itself will crash.

https://pastebin.com/veAzpH8J

**Comment by MattCzyr** [comment]
Sounds like `max-tick-time` in your `server.properties` file is set too low (60 seconds). I recommend raising it significantly or setting it to -1 to disable the watchdog entirely.

Also, if searches are taking 60+ seconds to begin with, I think you should consider changing the values for `naturescompass.distanceModifier`, `naturescompass.maxSamples`, and `naturescompass.sampleSpaceModifier` in `naturescompass.cfg`. Changing these values will prevent searches from continuing that long in the first place. The comments by these values in the config have information on how changing them will affect performance. An easy fix is just to lower `maxSamples`.
