### ISSUE TITLE
Chunks Not Loading

### ISSUE THREAD

**Issue by TheLegendaryGrim** [MattCzyr/NaturesCompass#35]
So i have a problem. Every time i click search for a biome most chunks dont load even my mods dont work. Need Help.

**Comment by MattCzyr** [comment]
Searching for a biome is a pretty intensive process, and it can lag the game if a search takes too long. I recommend changing the values for `distanceModifier`, `maxSamples`, and `sampleSpaceModifier` in `naturescompass.cfg` to mitigate this, although it will have an adverse effect on search accuracy. An easy fix is just to lower `maxSamples`.

**Comment by TheLegendaryGrim** [comment]
thx m8
