### ISSUE TITLE
Crash when searching for a biome - both in Singleplayer and Multiplayer.

### ISSUE THREAD

**Issue by Raithion** [MattCzyr/NaturesCompass#39]
Upon searching for a biome using Nature's Compass, my Singleplayer game has these issues:
1. Game/server stops working (I can still move around, but items don't drop and nothing responds.)
2. The game freezes indefinitely.
3. The game does not respond and crashes.

Upon doing the same thing on my Multiplayer server, this happens:
1. The server immediately crashes and closes.

Crash reports:
Singleplayer ---> https://pastebin.com/uMMmPMjx
Multiplayer ---> https://pastebin.com/ziMZCKuJ

**Comment by MattCzyr** [comment]
Please try to replicate this using version 1.5.1 (on both sever and client) and let me know if it persists or not. I've had this issue reported a few times now, and I'm trying to figure out whether it's unique to 1.6.0 or if it is simply a performance configuration issue.

**Comment by Raithion** [comment]
Thanks for the suggestion! Version 1.5.1 works perfectly with no issues, on both my Singleplayer world and Multiplayer server.
