### ISSUE TITLE
Biome finding code copied from BoP

### ISSUE THREAD

**Issue by Adubbz** [MattCzyr/NaturesCompass#4]
Hi, it has been brought to our attention that your code for searching for a biome has been lifted (and modified) from BoP:

https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.12.x-7.0.x/src/main/java/biomesoplenty/common/util/biome/BiomeUtils.java#L88-L119 

vs

https://github.com/MattCzyr/NaturesCompass/blob/master/src/main/java/com/chaosthedude/naturescompass/util/BiomeUtils.java#L30-L58

We'd like this removed, as this violates our license, and we didn't grant permission for it either. Thanks.

**Comment by copygirl** [comment]
The function is small enough that it is debatable whether it, on its own, is actually protected by copyright. On top of that it's not a 1:1 copy. You'd certainly have to get lawyers involved and bring this to court to find out for sure.

**Comment by Adubbz** [comment]
I can appreciate that, it's certainly not my intention to bring anyone to court over this. 

My main issue here is not that code from BoP has been used, but rather it's been used as a significant component of another mod based around a very similar feature (I.e. our biome finder) without asking for our permission. This doesn't sit well with me personally, and it wasn't a member of our team that noticed it, but rather someone without any prior suggestion by us. To me that does at least raise an eyebrow.

It looks like it's all fine now though, thanks for listening @MattCzyr. I apologise if I overreacted to this, we've faced a few troubles with stealing recently (much more blatant than this though), and it's just a bit disheartening to see.

**Comment by copygirl** [comment]
@Adubbz: I understand, and sorry for barging in on this issue. I felt the need to say something since you implied you were legally in the right and may have sounded a little threatening. I'm mostly of the opinion that sharing is caring and this type of conflict isn't worth it for a game. My statement to have lawyers involved was silly, of course.

**Comment by Adubbz** [comment]
I understand. Hindsight is a wonderful thing, and admittedly I was rather blunt about it. It wasn't my intention to be threatening but I can understand that's how it came across.

In my mind, implementing the same idea as us whether intentionally or not (and hopefully improving on it) is great. And using our code for inspiration or taking snippets from it is cool too. But when both happen at the same time, that's when it makes it rather uncomfortable.

I highly doubt there were any bad intentions here (despite what my initially frustrated self might've believed), I mainly bring this up for my own peace of mind.

**Comment by MattCzyr** [comment]
Looks like I'm jumping into the conversation a bit late but I just wanted to add that, if anything, I should be the one apologizing! Back when I was originally developing this mod I was under the false impression that BoP was under a license that allowed for sharing, modifying/remixing, etc. But like you said, @Adubbz, hindsight is a wonderful thing, and I certainly should have either taken a closer look at the license, asked for permission to use elements of your biome finding code, or both. Sorry about all this, but hopefully it has been thoroughly resolved now.
