### ISSUE TITLE
Crash when try to find a biome 

### ISSUE THREAD

**Issue by FoxHound-s** [MattCzyr/NaturesCompass#40]
With the newest version 1.6.1 my game crash when i try to find a biome , I try to find a biome and nothing happens then my world kind a shutdown , cant mine cant eat then CTD

**Comment by Ravalli03** [comment]
Having same issue with new update, the game just gets stuck with no crash log.

**Comment by MattCzyr** [comment]
Just released version 1.6.2 to combat this issue. There's a new config field that specifies how many new chunks can be generated per search, and max distance is calculated a bit differently. Delete your config before updating and let me know if this fixes the issue for you.

**Comment by FoxHound-s** [comment]
Yes , latest update fix the the crash and the hang , thanks

**Comment by Ravalli03** [comment]
Tested the update, works great with no issues. THANKS!
