### ISSUE TITLE
Server Crash NoSuchMethod

### ISSUE THREAD

**Issue by GoldiePlay** [MattCzyr/NaturesCompass#41]
When Trying to start a Server with Version 1.6.1 it keeps crashing.

## Log

https://gist.github.com/GoldiePlay/0a1620282817d9e71dedd69f7a212cf5

**Comment by MattCzyr** [comment]
Thanks for bringing this to my attention. This will be fixed in 1.6.2 (soon), but localized biome names (i.e. Ocean or Birch Forest) will no longer be valid identifiers for disabled biomes in the config, only ID (i.e. 0) and unlocalized name (i.e. minecraft:ocean).

**Comment by GoldiePlay** [comment]
No Problem. Thanks for Fixing it :D. Great Mod btw. :)
