### ISSUE TITLE
Nature's Compass causing Server-Crash with Sponge

### ISSUE THREAD

**Issue by ImSpacee** [MattCzyr/NaturesCompass#46]
Usually i'd report this to SpongeForge, but this appears to be an issue with the mod "Nature's Compass" instead of SF itself.

SpongeForge allows plugins on Servers, we use this in our Network.
Heres a link: https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2

We're using Forge 1.12.2-2838 with SpongeForge 1.12.2-2838-7.1.8-RC3963 Mod.
We're also using the latest version of NaturesCompass.

Attaching a log below for you to look at, appears NC is adding/removing/getting data from the main server thread- something that shouldn't really be done.

**Comment by ImSpacee** [comment]
https://hastebin.com/degasobede.md

^ Using this modpack: https://www.technicpack.net/modpack/one-life-popular-smp.1297373
^ (even without foamfix, other mods etc it still occurs)

**Comment by NicolasNewman** [comment]
I was just about to make an issue with a similar log. Here is mine:
[latest.log](https://github.com/MattCzyr/NaturesCompass/files/3970537/latest.log)

**Comment by NicolasNewman** [comment]
It looks like it's caused by the following in BiomeUtils.searchForBiome:
`final Biome biomeAtPos = world.getChunkFromBlockCoords(pos).getBiome(pos, world.getBiomeProvider());`

I'll be testing my own fixes in the meantime.

**Comment by NicolasNewman** [comment]
I changed the above line to `final Biome biomeAtPos = world.getBiomeForCoordsBody(pos);` which seems to have resolved the issue on my end.

**Comment by NicolasNewman** [comment]
On second thought, would this proposed fix not be able to search on unloaded chunks? On testing, the only biomes that can be found are ones where chunks are loaded.

**Comment by MattCzyr** [comment]
There's a debug message when a search finishes that says, among other things, how many chunks have been generated, so that's one way to see if it only searches loaded chunks. I'll test the change on my end.

**Comment by MattCzyr** [comment]
@ImSpacee Please try this 1.7.0 beta file instead and let me know whether the issue is resolved:

https://www.dropbox.com/s/3el0p1h6xtpb2cl/NaturesCompass-1.12.2-1.7.0-beta.jar?dl=0

**Comment by ImSpacee** [comment]
@MattCzyr Sorry for the late response, i've only just woken up.

I can confirm that the file you sent **IS** working with SpongeForge now!
I can also confirm that the pull request from @NicolasNewman #45 is working incredibly well- even recognising my own personal biome mod.

Thanks a ton to both of you!
I look forward to the CF release. :)
