### ISSUE TITLE
Weird incompatibility with Wearable Backpacks mod

### ISSUE THREAD

**Issue by DarkPandaX** [MattCzyr/NaturesCompass#5]
I've also submitted this issue to the GitHub for Wearable Backpacks.

When using both mods together in 1.12, upon making the titular compass, it was a gray wearable backpack, and not the compass. It's such a bizarre conflict of mods that I'm not sure why the hell it would do this, so I figure perhaps there's something going on with one of the mods that should be looked into.
![2017-07-23_19 03 18](https://user-images.githubusercontent.com/30394830/28503770-95dcdf5c-6fda-11e7-9d59-4c3a35890c53.png)
![2017-07-23_19 03 29](https://user-images.githubusercontent.com/30394830/28503774-9eb580b6-6fda-11e7-8072-d88489a7e37c.png)

**Comment by MattCzyr** [comment]
Should be fixed with the next release in the next couple days.

**Comment by MattCzyr** [comment]
Fix has been released in version 1.5.0. Let me know if it persists.
