### ISSUE TITLE
Crash on compass load

### ISSUE THREAD

**Issue by sinsoffallengods** [MattCzyr/NaturesCompass#59]
[crash-2020-02-29_20.54.09-server.txt](https://github.com/MattCzyr/NaturesCompass/files/4271319/crash-2020-02-29_20.54.09-server.txt)

For server 1.15.2. Crashes as soon as you open up its UI to search for a biome.

Edit: Full server crash

**Comment by MattCzyr** [comment]
Just to be clear, this is only a server crash? The client connected to the server does not crash?

Is this an immediate thing, or does the server hang for some time before it crashes?

**Comment by sinsoffallengods** [comment]
Oooops. Thought I closed this, so to clarify it was a complete server crash, it immediately kicked all clients and then crashed about a minute later. Turned out to be I had loaded a version meant for 1.12.2 instead of 1.15.2. I.E... I am a moron.
Thanks for the great mod!
