### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Malabrace** [MattCzyr/NaturesCompass#61]
https://paste.dimdev.org/uyofekoduw.mccrash

The compass was stuck on searching, I stashed it in a storage block (a rustic cabinet to be exact). When I reopened the cabinet it was still searching. Closed the cabinet and BAM. Crash

**Comment by MattCzyr** [comment]
This issue was fixed in Nature's Compass version 1.8.5, please update the mod.

**Comment by Malabrace** [comment]
Thank you, I contacted the pack dev. If he doesn’t, I’ll update the mod personallyModpack: Just another whistle stop (if I didn’t say previously)Sorry to have bothered Inviato da Posta per Windows 10 Da: Matt CzyrInviato: giovedì 2 aprile 2020 00:22A: MattCzyr/NaturesCompassCc: Malabrace; AuthorOggetto: Re: [MattCzyr/NaturesCompass] Crash report (#61) This issue was fixed in Nature's Compass version 1.8.5, please update the mod.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
