### ISSUE TITLE
[1.15.2] Game keeps crashing upon opening world

### ISSUE THREAD

**Issue by Mysteriaa** [MattCzyr/NaturesCompass#67]
Sent this to the Forge discord and was told this was caused by this mod. I had the compass in my hotbar. Crashlog below.
https://paste.ee/p/200rx#s=0&l=10372

**Comment by MattCzyr** [comment]
Looking back at this issue, and it like the paste is no longer available. If you're still facing this issue, please reopen it with a new crashlog.
