### ISSUE TITLE
Doesnt show biomes for under garden mod

### ISSUE THREAD

**Issue by benbenlaw** [MattCzyr/NaturesCompass#71]
biomes from undergarden mod not able to be search with the compass

**Comment by MattCzyr** [comment]
Are you in the Undergarden dimension when you try to search for Undergarden biomes?

**Comment by benbenlaw** [comment]
yeah was in the dimesion and was in the biome i was looking for

**Comment by benbenlaw** [comment]
i didnt show any biomes from that mod

**Comment by MattCzyr** [comment]
> i didnt show any biomes from that mod

Do you that none of the mod's biomes appeared in the list of biomes in the compass GUI?

**Comment by benbenlaw** [comment]
Yeah none of there biomes appear

**Comment by MattCzyr** [comment]
Just tested this myself, and everything worked as intended. I was able to find all the Undergarden biomes in the Nature's Compass GUI, and was able to search for them. Please ensure that you're using the latest versions of both mods. You can also sort the biomes in the GUI by source mod if you want to find them more easily.
