### ISSUE TITLE
[1.12] Compass doesn't locate correct biomes. It points to a random biome.

### ISSUE THREAD

**Issue by EnderBro123** [MattCzyr/NaturesCompass#75]
Title says all. I'm pointed to a completely random biome, even after selecting the biome I want.

**Comment by MattCzyr** [comment]
What does the information in the top left corner say after you search for a biome?

**Comment by EnderBro123** [comment]
Hello.

Sorry for the late response.

Anyway, attempting to locate biomes, simpli points me to a random area, rather then the biome I want.

![2020-12-01_10 48 19](https://user-images.githubusercontent.com/51277766/100783670-eeeb4480-33c2-11eb-8a14-b926431f96b7.png)
As you can see, this is a Project Vibrant Journeys Aspen Grove biome, which isn't what I searched for and selected.
I wanted a BOP Mangrove.

**Comment by EnderBro123** [comment]
@MattCzyr No response since 2 days. Mentioning incase.

**Comment by MattCzyr** [comment]
According to the compass info in the top left, the search hasn't completed. Does it ever complete, given enough time? If not, can you send the console log starting from the time you begin the search and ending a few minutes after that? There should be some clues in the log.

**Comment by EnderBro123** [comment]
The search basically never ends.

**Comment by EnderBro123** [comment]
@MattCzyr ^

**Comment by MattCzyr** [comment]
I see that you're in an ocean, but that's not the location the compass is pointing you to. The information on your HUD shows you that the mangrove is 2781 blocks away, at coordinates -6084, 2241. Go to that location and see if it's a mangrove.

**Comment by EnderBro123** [comment]
Tried again, was taken to a Mangrove.

The compass item itself is being dumb, apparently.

**Comment by MattCzyr** [comment]
In general you should refer to the information displayed on the HUD, not solely on the direction the compass is facing, although it should be pointing to the same location as displayed on the HUD. Closing this issue for now.

**Comment by EnderBro123** [comment]
Well, at least try to see if the item can be fixed.

**Comment by Arkytek** [comment]
> Well, at least try to see if the item can be fixed.

bruh it literally says found BECAUSE you ran past it... are you maybe on the spectrum?
it also says that your distance is 2761 blocks away because you had ran passed it......
