### ISSUE TITLE
Format Example For Blacklist

### ISSUE THREAD

**Issue by CynicalShrew** [MattCzyr/NaturesCompass#76]
It'd be nice to have an example for how to format the blacklist. I'm trying to blacklist about a dozen biomes, but the game crashes no matter how I try formatting it. Do you do ["minecraft:ocean", "minecraft:desert"]? Or without quotes? Or without a space between the comma? How is this supposed to be formatted? The game crashes if the blacklist isn't formatted correctly, so it's kind of important to know.

Edit: On further inspection, the cause was a missing quotation mark. The format I listed was correct, if anyone else has this issue. With quotes and a space. Consider this issue solved.

**Comment by MattCzyr** [comment]
Fixed with commit [5bd7e97](https://github.com/MattCzyr/NaturesCompass/commit/5bd7e978be38405577bac38231316dabde5e99e0), will be included in the next update.
