### ISSUE TITLE
NatureCompass crashes server randomly 

### ISSUE THREAD

**Issue by zespy12** [MattCzyr/NaturesCompass#78]
Hi , sorry for the lack of info but this is all I got. My server is running on sponge and I don't know how to reproduce it just it just happend randomly , I'll try to get more info if needed 
Here's the log : https://paste.gg/p/anonymous/54eae90611984e04b3a7e995ac516771

**Comment by MattCzyr** [comment]
Please update the mod, this issue was fixed in version 1.8.5.
