### ISSUE TITLE
Cant access any other biomes

### ISSUE THREAD

**Issue by WizardWar** [MattCzyr/NaturesCompass#82]
Im using Sevtech:ages and im trying to find other biomes but it only lists the darklands biomes. Is there a way to fix this?

**Comment by MattCzyr** [comment]
Please let me know what version you're using, and check the config to make sure no biomes are blacklisted.

**Comment by Macleykun** [comment]
Looked up this [modpack](https://www.curseforge.com/minecraft/modpacks/sevtech-ages). Last update was on Sep 1, 2020. Given the issue was made in 2021 it's safe to assume he used the latest modpack. Which contained the following version of NaturesCompass: NaturesCompass-1.12.2-1.5.1.jar

**Comment by MattCzyr** [comment]
Closing this as it has been inactive for a while and is based on an old version. If I had to guess, I'd say it is a config issue.
