### ISSUE TITLE
Unknown Crash related to Nature's Compass

### ISSUE THREAD

**Issue by Sniffity** [MattCzyr/NaturesCompass#84]
[crash-2021-03-12_00.59.00-client.txt](https://github.com/MattCzyr/NaturesCompass/files/6128825/crash-2021-03-12_00.59.00-client.txt)

Experienced an unknown crash related to Nature's Compass, while browsing the different biomes. Crash repeats upon relaunching the game and browsing through biomes again. Unsure with regards to the cause.

**Comment by MattCzyr** [comment]
Should be fixed in version 1.6.5-1.9.0.
