### ISSUE TITLE
Conflict with NoMoreRecipeConflicts

### ISSUE THREAD

**Issue by darthvader45** [MattCzyr/NaturesCompass#86]
I've tested this mod and NoMoreRecipeConflicts together and it seems this mod disables the functionality of the arrow NMRC adds to the crafting GUI.  I cannot switch between alternative recipes and as such the mod is useless.  If this could be fixed, I'd be able to use the mods together.  Until then, this mod is only a temporary addition until a biome I want to find is found.

**Comment by MattCzyr** [comment]
Tested this myself and couldn't recreate the issue. Just to clarify, you're talking about [this mod](https://www.curseforge.com/minecraft/mc-mods/stimmedcow-nomorerecipeconflict) for 1.12.2?

**Comment by darthvader45** [comment]
You can close this, tested right after finding and reporting the bug, and
it suddenly started working again.  Haven't had the issue since.
Golden rule in Minecraft: Never dig straight down.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
