### ISSUE TITLE
Nature's Compass can't find the Biomes in the "The Other"

### ISSUE THREAD

**Issue by Arceus73** [MattCzyr/NaturesCompass#88]
So yeah, I am playing All The Mods 6 and wanted to locate a Basalt Deltas Biome in the The Other dimension but it said not found. Then there is a Biome in The Other called The Other but this Biome is also not in the Nature's Compass. I asked in the atm6 Discord but no one knew why this is.

**Comment by MattCzyr** [comment]
Can you give me a link to the mod that adds these biomes? I'm not able to find it myself.

**Comment by Macleykun** [comment]
Believe he means this mod: https://www.curseforge.com/minecraft/mc-mods/allthemodium
Looked up the Other dimension from ATM6 and found this video: https://youtu.be/TXLr37e_I10?t=403

**Comment by Arceus73** [comment]
Yeah that's right. Sry for not answering for so long. The biome itself is the Vanilla one i guess but taken into another dimension from the mod Macleykun linked.

**Comment by thevortex** [comment]
its a datapack dimension, and the biomes are also datapack so i am not sure if that helps in figuring out why the compass can't see them.

**Comment by MattCzyr** [comment]
Seems to be an issue of datapack biomes not appearing in `WorldGenRegistries.BIOMES` or `ForgeRegistries.BIOMES`, where the mod pulls its biomes from. I'll look into how to obtain a registry of datapack biomes.

**Comment by MattCzyr** [comment]
Fixed in version 1.6.5-1.9.0.
