### ISSUE TITLE
Ultra Amplified Dimension for 1.16.5

### ISSUE THREAD

**Issue by ClaudiusMinimus** [MattCzyr/NaturesCompass#89]
Please add support for [Ultra Amplified Dimension - Forge](https://www.curseforge.com/minecraft/mc-mods/ultra-amplified-mod) 

MC 1.16.5

I  use the Ultra Amplified Dimension (Forge) for two mod packs [Survival in Chaos](https://www.curseforge.com/minecraft/modpacks/survival-in-chaos) and a new pack I am working on and would like to have your mod in my packs.

Thanks,
CM

**Comment by MattCzyr** [comment]
Seems to be related to #88, with datapack biomes not appearing in the regular biome registries. I'll look for a workaround.

**Comment by MattCzyr** [comment]
Fixed in version 1.6.5-1.9.0.
