### ISSUE TITLE
[1.16.5] Server crashes when using the compass?

### ISSUE THREAD

**Issue by Gbergz** [MattCzyr/NaturesCompass#97]
Title^
Not sure what causes them other than the crashlog mentioning this mod. Reporting this here to see what can unfold.

**Crash-Report:** https://gist.github.com/Gbergz/6e53ca972793a8d8f078c546b101aba3

**Minecraft** 1.16.5
**Forge** 36.1.31
**Natures Compass** 1.9.0

Modpack: [[Modpack]](https://www.curseforge.com/minecraft/modpacks/tnp-limitless-3)

**Comment by MattCzyr** [comment]
Fixed in version 1.9.1.
